from .add import Add
from .jr import Jr
from .mips_and import And
from .nor import Nor
from .mips_or import Or
from .sll import Sll
from .slt import Slt
from .srl import Srl
from .slt import Slt
from .srl import Srl
from .sub import Sub
from .mul import Mul
from .div import Div
from .mflo import Mflo
from .mfhi import Mfhi
from .xor import Xor
from .addu import Addu
from .sgt import Sgt
from .RMipsInstruction import RMipsInstruction
