from .comment import Comment
from .systemCall import Systemcall
from .SpecialInstruction import SpecialInstruction
from .la import La
from .move import Move
from .mfc1 import Mfc1
from .mtc1 import Mtc1
from .cvt_s_w import Cvt_s_w
from .cvt_w_s import Cvt_w_s
