from .addi import Addi
from .andi import Andi
from .beq import Beq
from .bne import Bne
from .lw import Lw
from .ori import Ori
from .slti import Slti
from .sw import Sw
from .addiu import Addiu
from .lb import Lb
from .lui import Lui
from .sltiu import Sltiu
from .li import Li
from .mips_not import Not
from .neg import Neg
from .IMipsInstruction import IMipsInstruction
from .sb import Sb
