from .addi import Addi
from .andi import Andi
from .beq import Beq
from .bne import Bne
from .lw import Lw
from .ori import Ori
from .slti import Slti
from .sw import Sw
from .addiu import Addiu
from .lb import Lb