name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
          cache: 'pip' # caching pip dependencies
      - uses: actions/setup-java@v4.2.1
      - uses: actions/setup-java@v4.2.1

      - run: pip install -r requirements.txt
      - run: sudo apt install build-essential
      - run: sudo apt install llvm
      - run: sudo apt install default-jre -y
      - run: sudo apt install default-jdk -y
      - run: python3 -m unittest discover -v
